### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [j-zygmunt/Mastermind#1]
1. `import copy as cp` — bez przesady, da się pisać 2 litery więcej przy używaniu tej nazwy.
2. Stałe w stylu 4, 6, 12 itp. nazwać.
3. Przemianowałbym klasę `GameRules` np. na `BasePlayer`.
4. Dobry początek, ale co z inteligencją komputera? W obecnym stanie projekt się nie nadaje na zaliczenie.

**Comment by j-zygmunt** [comment]
Szanowny Panie Doktorze,
Zamieściłem ukończony projekt (wraz z kilkoma testami), jeśli to możliwe to prosiłbym o jego ocenę. Wysyłałem kilka dni temu do pana maila o podobnej treści ale najwidoczniej gdzieś przepadł :)
Z wyrazami szacunku,
Jakub Zygmunt

**Comment by MarcinCiura** [comment]
LGTM. Gratuluję, jest Pan dwudziesty siódmy.

W wolnej chwili: w testach docstringi są zbędne; komentarze lepiej robić przez komentarze (`#`) zamiast stringów; dodać na końcu pliku z testami dwa magiczne wiersze. Na przyszłość: pobieracze w klasach są najczęściej zbędne.

Dodatkowa prośba: jeśli nikt tego przed Panem nie zrobi, proszę ogłosić konsultacje w niedzielę o 20:30 i w poniedziałek o 12:00 pod standardowym linkiem. Dziękuję!
